spring:
  cloud:
    gateway:
      routes:
        - id: pass_member_service
          uri: http://localhost:8081
          predicates:
            - Path=/no_auth/**
          filters:
            - StripPrefix=1
        - id: member_service
          uri: http://localhost:8081
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
              args:
                allowedRoles:
                  - USER
                  - ADMIN
        - id: email_service
          uri: http://localhost:8082
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
              args:
                allowedRoles:
                  - USER
                  - ADMIN
        - id: pass_email_service
          uri: http://localhost:8082
          predicates:
            - Path=/email_auth/**
          filters:
            - StripPrefix=1